name: Java CI with Maven + Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

  sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run SonarCloud Scan
      run: | 
        mvn clean verify sonar:sonar -DskipTests \
        -Dsonar.projectKey=Natan-TI_matchinvestV2 \
        -Dsonar.organization=natan-ti \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  sca:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run OWASP Dependency Check
      run: mvn verify -DskipTests
    - name: Upload SCA Report
      uses: actions/upload-artifact@v3
      with:
        name: sca-report
        path: target/dependency-check-report.html

  dast:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Spring Boot App
      run: mvn spring-boot:run -DskipTests &
    - name: Wait for app
      run: sleep 30
    - name: Run OWASP ZAP Scan
      run: docker run --rm -v $(pwd):/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://host.docker.internal:8080 -r zap_report.html
    - name: Upload DAST Report
      uses: actions/upload-artifact@v3
      with:
        name: dast-report
        path: zap_report.html
